name: compile C Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: main
        env:
          # Specify the Node.js version for the action
          node-version: 16

      - name: compile Hello World Program
        run: |
          gcc -o helloworld helloworld.c
        working-directory: ${{ github.workspace }}
