name: Compile C Program

on:
  push:
    branches:
      - main
      jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      -     - name: Compile Hello World Program
        run: |
          gcc -o helloworld helloworld.c
        working-directory: ${{ github.workspace }}
